[package]
name = "maplibre_native"
version = "0.1.1"
description = "Rust bindings to the MapLibre Native map rendering engine"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
repository = "https://github.com/nyurik/maplibre-native-rs"
edition.workspace = true
license.workspace = true
keywords = ["maplibre", "rendering", "gis", "tiles"]
categories = ["external-ffi-bindings", "science::geo", "rendering"]
rust-version = "1.81"
exclude = ["maplibre-native/", ".gitmodules"]

[features]
default = [] # automatically picks the platform-specific features
metal = []   # default on Apple platforms, do not add to default features
opengl = []
vulkan = []  # default on other platforms

[dependencies]
cxx.workspace = true

[dev-dependencies]

[build-dependencies]
cargo_metadata.workspace = true
cmake.workspace = true
cxx-build.workspace = true
flate2.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
ureq = { workspace = true, features = ["json"] }
walkdir.workspace = true

[lints]
workspace = true

[package.metadata.mln]
repo = "maplibre/maplibre-native"
release = "core-12e0922fc4cadcd88808830e697cfb1d5206c8c9"
static-lib = "libmaplibre-native-core-{target}-{graphics_api}.a"
static-headers = "maplibre-native-headers.tar.gz"

##########################################################
##########################################################
####  Workspace configuration for the entire project  ####
##########################################################
##########################################################

[workspace]
members = [".", "build_tester", "examples/*"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
cargo_metadata = "0.19.2"
clap = { version = "4.5.27", features = ["derive", "env", "unstable-markdown"] }
cmake = "0.1"
cxx = "1.0.138"
cxx-build = "1.0.138"
flate2 = "1.1.1"
maplibre_native = { path = ".", version = "0.1.0" }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10"
tar = "0.4.44"
ureq = "3.0.12"
walkdir = "2.5.0"

[workspace.lints.rust]
unused_qualifications = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_panics_doc = "allow"                 # FIXME: remove
