// Define a struct to hold window size
export struct Size {
    width: length,
    height: length,
}

// TODO: make this not global, because then it can be used only for one instance!
export global MapAdapter {
    in-out property <image> map_texture;
    callback mouse_press(x: float, y: float);
    callback mouse_move(x: float, y: float, bool);
    callback wheel_zoom(x: float, y: float, zoom_delta: float); // Positive delta_y: zoom out; Negative: zoom in
}

component MapWidget {
    // Default size
    // background: green;

    // Expose map image area size so backend can match framebuffer size
    out property<Size> map-size: { width: map.width, height: map.height };
    callback map-size-changed(Size);
    changed map-size => {
        map-size-changed(map-size);
    }

    VerticalLayout {
        spacing: 0px;

        map := Image {
            source: MapAdapter.map_texture;
            image-fit: fill;
            vertical-alignment: center;
            horizontal-alignment: center;

            touch := TouchArea {
                mouse-cursor: self.pressed ? grabbing : grab;

                pointer-event(e) => {
                    if (e.kind == PointerEventKind.down) {
                        MapAdapter.mouse_press(self.mouse-x / 1px, self.mouse-y / 1px);
                    } else if (e.kind == PointerEventKind.move && self.pressed) {
                        MapAdapter.mouse_move(self.mouse-x / 1px, self.mouse-y / 1px, e.modifiers.control);
                    }
                }

                // Mouse-wheel / trackpad scroll to zoom
                scroll-event(event) => {
                    MapAdapter.wheel_zoom(self.mouse-x / 1px, self.mouse-y / 1px, event.delta_y / 1px);
                    return accept;
                }
            }
        }
    }
}

export component MainWindow inherits Window {
    callback map-size-changed <=> map.map-size-changed;
    out property <Size> map-size <=> map.map-size;

    preferred-width: 800px;
    preferred-height: 600px;

    init => {
        debug("MainWindow width: ", self.width, ", Height: ", self.height);
    }

    map:= MapWidget {
        width: root.width;
        height: root.height;
    }

    Image {
        x: 10px;
        y: 10px;
        width: 100px;
        source: @image-url("slint-logo-simple.svg");
    }
}
