[package]
name = "build_helper"
version = "0.0.0"
publish = false
description = "Unpublished tester for the build.rs functions"
edition.workspace = true
license.workspace = true

[lints]
workspace = true
